#!/usr/bin/env bash
#
# This is a run script for
#      x1. setting up gem5
#      x2. setting up architecture
#      x3. kicking off cache creation
#      x4. running simulation using python script
#      x5. reading the statistics of the simulation 
#
#

_file=${0##*/}
error(){ echo "$_file: $@" ; exit 1 ; }

usage=\
"Usage: ./run_script.sh [option]=[type of option] 
	
	-a or --architecture  : ARM X86
	-c or --core          : number of cores
	-cp or --config-path  : path to configuration file 


	example:

	./run_script.sh -a=ARM
	./run_script.sh -a=ARM -c=4 
	./run_script.sh -a=ARM -c=4 -cp=run.config
	./run_script.sh -a=ARM -c=2 -cp=/path-to-file/
	./run_script.sh -cp=/path-to-file/
"

check_build(){
    #
    # This executable that is created is needed to run
    # python, source, and simulation
    #
    if ! [ -e gem5/build/$architecture/gem5.opt ] ; then
	echo "$_file: Build doesnt exist: Creating build executable ..."
	scons build/$architecture/gem5.opt -j$core || \
	    error "Building executable failed: View error above"
    fi
}

start_sim(){
    #
    # This block starts the simulation. 
    # Using executable created by gem5, and our configuration file.
    # the output of the simulation is saved in the run.log file. 
    #
    cp run_single_core.py gem5/configs/run_single_core.py #save config amongst other config
    gem5/build/$architecture/gem5.opt gem5/configs/run_single_core.py run.config |& tee run.log 
}

create_data(){
    #
    # Saving the data results generated by the simulator in the
    # separate directory within the top level.
    #
    if ! [ -d gem5/m5out ] ; then error "output hasnt generated" ; fi
    local data_dir="DATA_RESULT_$(date '+%Y%m%d%H%M%S')" 
    mv m5out $data_dir
    cp run.log $data_dir/.
}


#default parameters
architecture='X86'
core=2
config_path="run.config"

if [ $# -eq 0 ] ; then error "$usage" ; fi  
for argument in "$@"
do
    case $argument in
	-a=*|--architecture=*)
	    architecture="${argument#*=}"
	    shift ;;
	-c=*|--core=*)
	    core="${argument#*=}"
	    if ! [[ $core =~ ^[0-9]+$ ]] ; then
		echo "$usage" ; error "Invalid numerical value : $argument"
	    fi
	    shift ;;
	-cp=*|--config-path=*)
	    config_path="${argument#*=}"
	    if ! [ -e $config_path ] ; then
		echo "$usage" ; error "Invalid path location : $argument"
	    fi
	    shift ;; 
	*)
	    echo "$usage" ; error "Invalid arguments : $argument "
	    shift ;;
    esac
done

echo " Peforming simulation run using : $architecture ISA"  
echo " Using configuration file       : $config_path"

check_build
start_sim
create_data


